name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
    deploy-job:
      runs-on: ubuntu-latest
      steps:
        
                 
        - name: Netlify Deploy
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_DEPLOY_TO_PROD: true
            publish-dir: './files'
            production-branch: master
            deploy-message: "Deploy from GitHub Actions"
            enable-pull-request-comment: false
            enable-commit-comment: true
            overwrites-pull-request-comment: true
          run: netlify deploy --prod
